### ISSUE TITLE
is this a joke?

### ISSUE THREAD

**Issue by raegen** [tc39/proposal-array-filtering#3]
- Name one programming language that has a different interface for filter.
- That is because filter by definition returns a subset of elements of the given data structure, for which a given predicate returns **true**.

**Comment by jridgewell** [comment]
Your tone reads as hostile, please remember the [code of conduct](https://tc39.es/code-of-conduct/).

> Name one programming language that has a different interface for filter.

https://github.com/jridgewell/proposal-array-select-reject#related

> That is because filter by definition returns a subset of elements of the given data structure, for which a given predicate returns true.

I'm not proposing we change `filter`. I'm saying its naming is problematic, because when I read `array.filter()`, I think it's filtering out the things that return `true`.

**Comment by raegen** [comment]
I apologize, but I really wasn’t sure if it was a joke. 
But you cleared that up.
Let me get this straight, you’re proposing a name change of a method whose name and interface do not stem from the language in question, but from the functional paradigm itself - it’s ‘filtering in’, as you call it, in every other functional language (mind Ruby) -because You find it confusing?

**Comment by jridgewell** [comment]
> you’re proposing a name change of a method

I'm proposing an alias. `Array.p.filter` won't change, this only adds `Array.p.select` which does the same thing. They'd literally be the same function instance: `Array.prototype.filter === Array.prototype.select`.

> ..in every other functional language (mind Ruby) -because You find it confusing?

I'm proposing it because there was some agreement on the TC39 IRC. Judging by the number for project stars (it's been less than 48 hours), I'm not the only one who finds it confusing.

**Comment by lifaon74** [comment]
Hum sorry to tell this, but this looks bad to me: introducing new methods for... nothing. I mean 'filter' is clear enough. You're adding a new layer of complexity...
